# Generated by Django 3.0.8 on 2020-08-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atomicNumber', models.IntegerField()),
                ('symbol', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=1000)),
                ('img_url', models.CharField(max_length=200)),
            ],
        ),
    ]
