# Generated by Django 3.0.8 on 2020-08-16 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='description',
        ),
        migrations.RemoveField(
            model_name='element',
            name='img_url',
        ),
        migrations.AddField(
            model_name='element',
            name='atomicMass',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='element',
            name='elementBlock',
            field=models.CharField(default='s', max_length=1),
        ),
        migrations.AddField(
            model_name='element',
            name='groupNumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='element',
            name='periodNumber',
            field=models.IntegerField(default=0),
        ),
    ]
